name: Test Text2Audio

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build application 
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Display python version
        run: python -c "import sys; print(sys.version)"


